# Generated by Django 4.2 on 2023-07-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sendmailsmodel_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmailsmodel',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
